import { PROFILE_APP_KEY, PROFILE_APP_ROOT, PROFILE_CLASS_KEY, PROFILE_CLASS_ROOT, PROFILE_CMDT_KEY, PROFILE_CMDT_ROOT, PROFILE_CSET_KEY, PROFILE_CSET_ROOT, PROFILE_FIELD_KEY, PROFILE_FIELD_ROOT, PROFILE_LAYOUT_KEY, PROFILE_LAYOUT_ROOT, PROFILE_OBJECT_KEY, PROFILE_OBJECT_ROOT, PROFILE_PAGE_KEY, PROFILE_PAGE_ROOT, PROFILE_RECTYPE_KEY, PROFILE_RECTYPE_ROOT, PROFILE_TAB_KEY, PROFILE_TAB_ROOT, PROFILE_USERPERM_KEY, PROFILE_USERPERM_ROOT } from "./constants_profiles";

export const PROFILE_KEY_TYPE = {
    [PROFILE_APP_ROOT]: { key: PROFILE_APP_KEY, typename: "CustomApplication"},
    [PROFILE_CLASS_ROOT]: { key: PROFILE_CLASS_KEY, typename: "ApexClass" },
    [PROFILE_CMDT_ROOT]: { key: PROFILE_CMDT_KEY, typename: "CustomObject"},
    [PROFILE_CSET_ROOT]: { key: PROFILE_CSET_KEY, typename: "Settings" }, // ?? 
    [PROFILE_FIELD_ROOT]: { key: PROFILE_FIELD_KEY, typename: "CustomField" },
    [PROFILE_LAYOUT_ROOT]: {  key: PROFILE_LAYOUT_KEY, typename: ["Layout", "RecordType"] },
    [PROFILE_OBJECT_ROOT]: {  key: PROFILE_OBJECT_KEY, typename: "CustomObject" },
    [PROFILE_PAGE_ROOT]: {  key: PROFILE_PAGE_KEY, typename: "ApexPage" },
    [PROFILE_RECTYPE_ROOT]: { key: PROFILE_RECTYPE_KEY, typename: "RecordType" },
    [PROFILE_TAB_ROOT]: {  key: PROFILE_TAB_KEY, typename: "CustomTab" },
    [PROFILE_USERPERM_ROOT]: {  key: PROFILE_USERPERM_KEY } // ??
}